"""
Database Schemas

Define your MongoDB collection schemas here using Pydantic models.
These schemas are used for data validation in your application.

Each Pydantic model represents a collection in your database.
Model name is converted to lowercase for the collection name:
- User -> "user" collection
- Product -> "product" collection
- BlogPost -> "blogs" collection
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict

# Example schemas (keep for reference)

class User(BaseModel):
    """
    Users collection schema
    Collection name: "user" (lowercase of class name)
    """
    name: str = Field(..., description="Full name")
    email: str = Field(..., description="Email address")
    address: str = Field(..., description="Address")
    age: Optional[int] = Field(None, ge=0, le=120, description="Age in years")
    is_active: bool = Field(True, description="Whether user is active")

class Product(BaseModel):
    """
    Products collection schema
    Collection name: "product" (lowercase of class name)
    """
    title: str = Field(..., description="Product title")
    description: Optional[str] = Field(None, description="Product description")
    price: float = Field(..., ge=0, description="Price in dollars")
    category: str = Field(..., description="Product category")
    in_stock: bool = Field(True, description="Whether product is in stock")

# Crypto Trading Tip schema

class TradingTip(BaseModel):
    """
    Crypto trading tips generated by the system
    Collection name: "tradingtip"
    """
    symbol: str = Field(..., description="Crypto symbol, e.g., BTC, ETH")
    timeframe: str = Field(..., description="Requested timeframe, e.g., 1h, 4h, 1d")
    price: float = Field(..., description="Current price in USD at the time of generation")
    indicators: Dict[str, float] = Field(default_factory=dict, description="Calculated indicators like SMA/RSI")
    signal: str = Field(..., description="buy, sell, or neutral")
    confidence: float = Field(..., ge=0, le=1, description="Confidence score between 0 and 1")
    tip: str = Field(..., description="Human-readable recommendation text")
    notes: Optional[str] = Field(None, description="Optional extra notes or warnings")

# Note: The Flames database viewer can read these via /schema endpoint if exposed
